kind: pipeline
type: exec
name: default

node:
  exe: exe

clone:
  disable: true

steps:
- name: clone
  commands: '''|
  if [[ -d /gameci/drone/unity_project_template ]]; then
    git -C /gameci/drone/unity_project_template push
  else
    git clone https://github.com/wolfired/unity_project_template.git /gameci/drone/unity_project_template
  fi'''
