kind: pipeline
type: exec
name: default

# environment:
#   http_proxy: http://192.168.73.39:1080
#   https_proxy: http://192.168.73.39:1080
#   HTTP_PROXY: http://192.168.73.39:1080
#   HTTPS_PROXY: http://192.168.73.39:1080

node:
  exe: exe

clone:
  disable: true

steps:
- name: clone
  commands:
  - bash -ic 'if [[ -d /gameci/drone/unity_project_template ]]; then git -C /gameci/drone/unity_project_template pull; else git clone https://github.com/wolfired/unity_project_template.git /gameci/drone/unity_project_template; fi'

- name: build
  commands:
  - bash -ic 'source /root/.bashrc; timestamp=`date +%Y%m%d_%H%M%S` unity_exe_file=/usr/bin/unity-editor dot_prj_name_core=dot_prj_core dot_prj_name_mods=dot_prj_mod0,dot_prj_mod1 dot_prj_name_editor=dot_prj_editor unity_log_file= u3d_prj_name=u3d_prj u3d_build_target=Win64 u3d_out_file_name=${u3d_prj_name}_${timestamp}.exe u3d_prj_builder_script=com.wolfired.dot_prj_stage1.DefaultWindowsBuilder.Build server_endpoint=192.168.180.25:10080 server_namespace_prefix= server_enable_download=true server_enable_upload=true step_env_prepare=0 step_activate_unity=0 step_create_unity_prj=1 step_dotnet_refs=1 step_install_unity_package=1 step_create_dotnet_prj=1 step_build_dotnet_prj=1 step_create_default_scene=1 step_build_unity_prj=1 step_upload=1 bash /gameci/drone/unity_project_template/main.sh'
