kind: pipeline
type: docker
name: default

steps:
- name: test
  image: unityci/editor:ubuntu-2021.2.7f1-windows-mono-0.15.0
  # mem_limit: 8589934592
  commands:
  # - apt-get install net-tools
  # - ifconfig
  # - curl --socks5-hostname clash.wolfired.com:1080 https://www.google.com.hk
  # - export http_proxy=http://192.168.1.7:1080
  # - export https_proxy=http://192.168.1.7:1080
  # - unity-editor -logFile - -quit -batchmode -manualLicenseFile /drone/src/Unity_v2021.x.ulf | true
  # - unity-editor -logFile - -quit -batchmode -projectPath /drone/src -buildTarget Win -executeMethod Main.Test
  - bash /drone/src/main.sh
