kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
- name: build
  image: unityci/editor:ubuntu-2019.4.6f1-android-0.15.0
  commands:
  - unity_exe_file=/usr/bin/unity-editor unity_log_file=u3d_editor.log dot_prj_name_core=slg_dot_core dot_prj_name_mods=slg_dot_mod0,slg_dot_mod1 dot_prj_name_editor=slg_dot_editor bash /drone/src/main.sh
