kind: pipeline
type: exec
name: default

environment:
  http_proxy: http://192.168.73.39:1080
  https_proxy: http://192.168.73.39:1080
  HTTP_PROXY: http://192.168.73.39:1080
  HTTPS_PROXY: http://192.168.73.39:1080

node:
  exe: exe

clone:
  disable: true

steps:
- name: clone
  commands:
  - bash -ic 'if [[ -d /gameci/drone/unity_project_template ]]; then git -C /gameci/drone/unity_project_template pull; else git clone https://github.com/wolfired/unity_project_template.git /gameci/drone/unity_project_template; fi'

- name: build
  commands:
  - bash -ic 'echo $PATH'
