kind: pipeline
type: exec
name: default

node:
  exe: exe

clone:
  disable: true

steps:
- name: clone
  commands:
  - git clone https://github.com/wolfired/unity_project_template.git /gameci/drone/unity_project_template


